### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by tarmacalastair** [teknologist/docker-webnut#2]
`docker run -e UPS_HOST="10.11.12.13" -e UPS_PORT="3493" -e UPS_USER="monuser" -e UPS_PASSWORD="secret" -p 6543:6543 -e teknologist/webnut:latest`

The above line tries to set an environment variable instead of the image name. So you need to remove the final _"-e"_ before the image name:
`docker run -e UPS_HOST="10.11.12.13" -e UPS_PORT="3493" -e UPS_USER="monuser" -e UPS_PASSWORD="secret" -p 6543:6543 teknologist/webnut:latest`

**Comment by teknologist** [comment]
Thanks
